Repository atomist/aspect-sdm, pull requests merged in 2019-10, with the labels that each got.

#27 Add Spring aspects
  index.ts
  lib/aspect/aspects.ts
  lib/aspect/common/frameworkAspect.ts
  lib/aspect/common/virtualProjectCountAspect.ts
  lib/aspect/git/branchCount.ts
  lib/aspect/git/gitClassificationAspect.ts
  lib/aspect/gradle/gradleBuildFile.ts
  lib/aspect/java/badApis.ts
  lib/aspect/maven/javaVersion.ts
  lib/aspect/maven/mavenDirectDependencies.ts
  lib/aspect/maven/mavenPlugins.ts
  lib/aspect/scorers.ts
  lib/aspect/spring/consoleLogging.ts
  lib/aspect/spring/defaultBannerTxtAspect.ts
  lib/aspect/spring/idioms.ts
  lib/aspect/spring/logbackAspect.ts
  lib/aspect/spring/reactiveWebUsageAspect.ts
  lib/aspect/spring/springBootApps.ts
  lib/aspect/spring/springBootStarter.ts
  lib/aspect/spring/springBootVersion.ts
  lib/aspect/spring/springClassificationAspect.ts
  lib/aspect/spring/twelveFactors.ts
  lib/aspect/spring/xmlBeans.ts
  lib/aspect/spring/yamlConfigFiles.ts
  lib/aspect/workspaceScorers.ts
  package-lock.json
  package.json
  test/aspect/common/buildToolAspect.test.ts
  test/aspect/common/ciAspect.test.ts
  test/aspect/common/frameworkAspect.test.ts
  test/aspect/gradle/gradleBuildFile.test.ts
  test/aspect/java/badApis.test.ts
  test/aspect/maven/mavenDirectDependencies.test.ts
  test/aspect/spring/consoleLogging.test.ts
  test/aspect/spring/logback.test.ts
  test/aspect/spring/springBootApps.test.ts
  test/aspect/spring/springProjects.ts
  test/aspect/spring/twelveFactors.test.ts
  test/aspect/spring/xmlBeanDefinitions.test.ts
Labels: changelog:added

#28 Allow ingestion of user orgs and default to configured github provider
  lib/command/ingestOrg.ts
  lib/graphql/query/githubProvider.graphql
Labels: auto-merge:on-approve, auto-rebase:on-push

#34 Check for GitHub.com provider type
  index.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:changed
